<?php
/**
 * @file
 * Default settings-php.inc file.
 */

/**
 * Edit a copy of this file with your own database credentials and save the result to
 * %webroot%/site-php/ilr/%your_drupal_root%/settings-php.inc.
 */
$databases = array (
  'default' => 
  array (
    'default' => 
    array (
      'database' => '',
      'username' => '',
      'password' => '',
      'host' => 'localhost',
      'port' => '',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);
